jenkins:
  systemMessage: "Controlled by Configuration as Code"
jobs:
  - script: >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }
  - url: https://raw.githubusercontent.com/kedark3/jcasc-example/master/seed.groovy

unclassified:
  ansibleTowerGlobalConfig:
    towerInstallation:
      - enableDebugging: true
        towerCredentialsId: ansible-tower-jenkins-user  # create these by hand in jenkins
        towerDisplayName: Infra-Ansible-Tower-01
        towerTrustCert: true
        towerURL: https://infra-ansible-tower-01.example.com